### ISSUE TITLE
ATG Biomes Overiding BiomeTweaker configs

### ISSUE THREAD

**Issue by nanakisan** [superckl/BiomeTweaker#30] opened 2015-07-08 00:14 UTC
http://i.imgur.com/PaMZuYx.png

I was testing out that interesting desert world script in the wiki. However while vanilla biomes are affected. ATG seems to have a slight conflict and generate it's biomes as normal.

**Comment by superckl** [comment] 2015-07-08 21:33
This is a duplicate of #1 due to the mods both being by @ted80. The author doesn't consult the BiomeManager at all.

Since this has been reported twice now, I'll look into adding compatibility on my end rather than waiting for the author to properly support Forge mechanics.

**Comment by nanakisan** [comment] 2015-07-08 21:45
Wait ATG isn't made by ted? This mod is made by TTFTCUTS as shown here
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291067-atg-alternate-terrain-generation  
  
Yer confusing this with RWG and BWG.

**Comment by superckl** [comment] 2015-07-08 21:56
Oh, my bad. That's embarrassing.

Anyway, ATG isn't open source as far as I can tell, so I really have no way to figure out why this is occurring. It's up to @TTFTCUTS. You may want to report this to him. If the source is somewhere, let me know and I'll look into it.

**Comment by nanakisan** [comment] 2015-07-08 22:01
Oh thats no problem. I've posted a notice on the forums leading back to this report. Mentioned I was the one at fault for reporting it here. Hopefully support comes shortly. BT and ATG together would be quite awesome to see.

**Comment by superckl** [comment] 2015-09-10 06:55
I'm going to go ahead and close this with the 'wontfix' tag. It's not in my control.

**Closed by superckl** 2015-09-10 06:55 UTC
Labels: compatibility, wontfix
