### ISSUE TITLE
BiomeTweaker Breaks AE's RF and Fluid P2P Tunnels

### ISSUE THREAD

**Issue by Pyr0Byt3** [superckl/BiomeTweaker#23] opened 2015-05-21 19:36 UTC
Applied Energistics' item, light, ME, and redstone P2P tunnels are fine, but the RF and fluid ones stop working as soon as BiomeTweaker is added (Tested with BiomeTweaker 0.9.97, Applied Energistics 2 rv2-stable-3, and Thermal Expansion 4.0.1-182).

Without BiomeTweaker:
https://youtu.be/dQSs3eRjqxo

After BiomeTweaker is added:
https://youtu.be/qwc07kXbHao

**Comment by superckl** [comment] 2015-05-21 19:49
Did you try it with just AE2, TE, and BT? (The video is in AS2 so it could be something else) I'm on a trip currently so I can't test this myself until Tuesday.

**Comment by Pyr0Byt3** [comment] 2015-05-21 19:54
I did. Made a pack with just those three mods to be sure. Same result.

**Comment by superckl** [comment] 2015-05-21 20:02
Can you try enabling light ASM mode for me? It's an option in BiomeTweaker.cfg.

Also, are you running any scripts?

**Comment by Pyr0Byt3** [comment] 2015-05-21 20:18
No tweaks. Just using the default config ("include":[]). Light ASM didn't fix the issue either, unfortunately.

**Comment by superckl** [comment] 2015-05-21 20:41
Well that is very strange. With no scripts and light ASM enabled, the only thing BiomeTweaker should touch is the BiomeGenBase class. I'll let you know when I can get around to troubleshooting this.

**Comment by Pyr0Byt3** [comment] 2015-05-21 20:49
Yeah, *really* strange. Had to go disabling everything in AS2 one-by-one to find the culprit. Not once did BT even cross my mind. Is there nothing else I can do to help?

**Comment by superckl** [comment] 2015-05-21 20:59
Since I can't open this up in a Dev environment, the only thing left would be a full log, including placing down test P2Ps.

**Comment by Pyr0Byt3** [comment] 2015-05-21 21:18
Okay, how would I go about getting that? Would [MultiMC's Log page](https://github.com/MultiMC/MultiMC5/wiki/Minecraft-Logs#minecraft-log-page) work?

**Comment by superckl** [comment] 2015-05-21 21:26
Yeah. Seems like all you need to do is press Upload once you've quit of the test world.

**Comment by Pyr0Byt3** [comment] 2015-05-21 21:33
Well, unfortunately, nothing happens in the log when I place down P2Ps, so I'm not sure how useful this will be: http://paste.ee/p/OokrJ

**Comment by superckl** [comment] 2015-05-21 21:57
Is light ASM enabled in that log? There is an error on line 399 that looks like the culprit.

**Comment by Pyr0Byt3** [comment] 2015-05-21 22:02
Yes, light ASM was enabled.

**Comment by superckl** [comment] 2015-05-21 22:07
Double check you've enabled it correctly. BiomeTweaker is doing superclass checking in that log and it shouldn't be with light ASM enabled.

If that still fails, try adding this class to the ASM blacklist:

    appeng/parts/layers/LayerISidedInventory_TileCableBus

**Comment by Pyr0Byt3** [comment] 2015-05-21 22:22
Yeah, just checked the config file: `"enable light asm":true,`. I changed the blacklist line to `"asm blacklist":["appeng/parts/layers/LayerISidedInventory_TileCableBus"],` and there's still runtime exceptions: http://paste.ee/p/6Hacm

**Comment by superckl** [comment] 2015-05-21 23:02
Eh, try changing 

    "enable light asm"

to

    "enable light ASM"

Might be a deep in my part...

**Comment by Pyr0Byt3** [comment] 2015-05-21 23:13
It crashes on startup now: http://paste.ee/p/6GWva

**Comment by superckl** [comment] 2015-05-21 23:19
So it turns out I've completely messed up the light ASM config. To get it to enable you're going to have to do this:

1. Keep the current entry "enable light ASM".
2. Create a new entry "lightASM" set to true.

Light ASM mode should enable then.

**Comment by Pyr0Byt3** [comment] 2015-05-21 23:28
Awesome, it works now! The ASM blacklist change isn't needed either. Thanks for replying to everything so quickly, btw. Enjoy your trip!

**Comment by superckl** [comment] 2015-05-21 23:30
Great to hear! I'll let you know when I manage to get a fix that doesn't require light ASM mode.

**Comment by yarma92** [comment] 2015-05-22 10:17
Just an update on this, the BiomeTweaker.cfg file that comes with as 2 only contains the following:
'{
    //If true, BiomeTweaker will generate separate files for each biome when creating the status report.
    "separate files":true,
    //An array of tweak files to include. An example tweak file is created along with this configuration file.
    "include" : ["ASOcean.cfg"]
}'
When adding/copying in the correct config into the file it then fails to launch MC when clicking play. The solution was to delete the config file and then launch AS2 again and it regens with correct config. You then have to add the ASOcean.cfg to the include, and add the light asm adjustments as mentioned above.

**Comment by Pyr0Byt3** [comment] 2015-05-22 13:59
Maybe you forgot a comma somewhere? This file works for me:
```
{
    //If true, BiomeTweaker will generate separate files for each biome when creating the status report.
    "separate files":true,
    "enable light ASM":true,
    "lightASM":true,
    //An array of tweak files to include. An example tweak file is created along with this configuration file.
    "include":["ASOcean.cfg"]
}
```

**Comment by yarma92** [comment] 2015-05-22 15:20
It was happening on two separate clients. We triple checked everything with no missing commas :/ Might just be AS2 being derpy. As i said deleting the config caused a full one to generate and then it worked fine. Just thought I would add the info to here as a reference for others in case.

**Comment by superckl** [comment] 2015-05-22 17:27
The config in AS2 is the one that came with the first versions on BiomeTweaker. Any options that are missing simply default to the value that should be there.

Where did you copy the config from? What text editor are you using? As I'm sure you know, JSON is very picky about spaces and tabs. Some text editors automatically interchange them.

**Comment by yarma92** [comment] 2015-05-22 23:22
Copied it off the repo, edited with notepad++

**Comment by superckl** [comment] 2015-05-23 15:50
Well, that's strange as well. The file on the repo is the file that gets packaged with BiomeTweaker and written to the disk. Perhaps Github has done something weird with the spacing. I would need an error message to know for sure though.

**Comment by superckl** [comment] 2015-05-23 17:26
Build 101 will now correctly read the "enable light asm" config field:

http://jenkins.superckl.me/job/BiomeTweaker/101/

I will close this issue when I release 1.0.

**Comment by Pyr0Byt3** [comment] 2015-05-23 17:48
Sweet. Downloading as we speak. Unfortunately, @jadedcat closed [my issue on AS2's tracker](http://minecraft.curseforge.com/modpacks/225550-agrarian-skies-2/issues/647). Not sure if I should PM her, open another issue, or what.

**Comment by superckl** [comment] 2015-05-29 19:20
Build 107 is confirmed to fix this issue in the latest Agrarian Skies (1.1.1)

http://jenkins.superckl.me/job/BiomeTweaker/107/

**Comment by alfw** [comment] 2015-06-05 23:13
@superckl can you push this release soon? it also breaking other stuff in build 97, reseting the problems with 112 fixes them.

**Comment by superckl** [comment] 2015-06-05 23:33
I'm planning to release 1.0 this weekend, provided I can get the needed time to fix everything still in the issue tracker.

**Comment by superckl** [comment] 2015-06-06 22:32
http://minecraft.curseforge.com/mc-mods/228895-biometweaker/files/2241592

**Closed by superckl** 2015-06-06 22:32 UTC
Labels: awaiting release, bug
