### ISSUE TITLE
Crash with QuiverBow & QuiverMob

### ISSUE THREAD

**Issue by Amaxter** [superckl/BiomeTweaker#5] opened 2015-04-15 00:29 UTC
http://hastebin.com/ucuyimesuy.profile
Let me know if you need any more details.

**Comment by superckl** [comment] 2015-04-15 01:22
Looks like ASM-Helper is unable to resolve ModelBase. Can you provide me with a method to reproduce this error myself?

**Comment by Amaxter** [comment] 2015-04-15 01:35
Install QuiverBow (http://wildwestscifi.net/coding/9889) as well with your mod and run it server side with Forge 1307.

**Comment by superckl** [comment] 2015-04-15 02:24
This is the fault of QuiverBows. The mod loads classes that should only be loaded on the client side, causing BiomeTweaker's ASM to be unable to resolve the super classes. This is a very bad thing to do, and you should go yell at the author for it.

I will add an error catch in BiomeTweaker's ASM transformer. BiomeTweaker will complain, but not crash.

**Comment by superckl** [comment] 2015-04-15 02:33
On second though, I'm going to tell the author to load his models properly, rather than wrapping entire sections of code in try-catch blocks. If he doesn't fix it, well that sucks. Stay tuned.

As of now, BiomeTweaker is not compatible with QuiverBows.

**Comment by Amaxter** [comment] 2015-04-15 10:47
Awesome, hope he's able to.

**Comment by superckl** [comment] 2015-04-18 17:30
This issue was inadvertently fixed with someone else I added. There is a new config option 'force modded colors' that you can disable on the server to fix this crash.

**Closed by superckl** 2015-04-18 17:30 UTC
Labels: bug
