### ISSUE TITLE
1.18+ Adding Features Doesn't Work

### ISSUE THREAD

**Issue by ZIsGoated** [superckl/BiomeTweaker#283] opened 2022-05-01 04:55 UTC
Adding features on 1.18 doesn't seem to work and i've almost certain i've tried everything. I even tried to add the feature from the example (the ancient debris feature) script to make sure it wasn't me, and it still wouldn't work. Not sure if it's me or if im missing something but it's just not working for me.

**Comment by superckl** [comment] 2022-05-01 06:01
It is working for me with the latest version. Please provide your scripts and the locations you are placing files. You may also try verifying these features are appearing in the biome output files.

**Comment by ZIsGoated** [comment] 2022-05-01 14:19
![Capture](https://user-images.githubusercontent.com/91098252/166149708-a486cd26-120f-43fa-a0af-274efcc9c685.PNG)
![Capture1](https://user-images.githubusercontent.com/91098252/166149775-d3854c7c-71b0-4fa2-ac75-25a96af0c302.PNG)
![Capture3](https://user-images.githubusercontent.com/91098252/166149810-62a82a35-0735-4cf2-be20-744ae971045b.PNG)
![image](https://user-images.githubusercontent.com/91098252/166149907-49a577c1-881a-491c-bffc-857f2b36395c.png)
![image](https://user-images.githubusercontent.com/91098252/166149928-bccd754f-6bc2-400a-a70b-32beb1740684.png)
![image](https://user-images.githubusercontent.com/91098252/166149939-a09da2d7-ec31-4dfe-a4fd-be783c3d4fcd.png)
![image](https://user-images.githubusercontent.com/91098252/166149951-7117577f-4803-4c27-bb3a-0c39db9291e8.png)
![image](https://user-images.githubusercontent.com/91098252/166149973-d9697425-7ffb-4a6b-be6d-1f58f836a71d.png)
![image](https://user-images.githubusercontent.com/91098252/166149980-11a78c29-c03c-4c2e-a447-ef609f256959.png)

**Comment by superckl** [comment] 2022-05-01 15:33
`Tweaker` needs to be capitalized.

**Comment by ZIsGoated** [comment] 2022-05-01 16:10
the netherite works now but not the baobob trees,  any suggestions?

**Comment by superckl** [comment] 2022-05-01 16:48
Read the tutorial more carefully. You cannot simply copy the entire output json. You only want to copy over what is inside the "configured_feature" or "placed_feature" blocks. You can look at the minecraft wiki page that is linked in the tutorial to see this as well.

**Comment by ZIsGoated** [comment] 2022-05-01 17:20
So essentially I would have to make a whole new config for the trees, etc?

**Comment by superckl** [comment] 2022-05-01 17:27
No, you simply need to modify what is in your json files appropriately. Since this is not a bug, I will be closing this issue. If you want more help this, please join the discord channel and we'll be happy to give you more assistance.

**Closed as completed by superckl** 2022-05-01 17:27 UTC

**Comment by ZIsGoated** [comment] 2022-05-01 17:42
Sounds good. Do you got a link to the server?

**Comment by superckl** [comment] 2022-05-01 17:45
It is on the wiki homepage.

https://github.com/superckl/BiomeTweaker/wiki
